spring:
  security:
    oauth2:
      client:
        registration:
          reddit:
            client-id: #
            client-secret: #
            client-name: hrp402_test
            provider: reddit
            authorization-grant-type: client_credentials
            username: #
            password: #
            scope:
              - identity
              - modlog
              - wikiedit
        provider:
          reddit:
            token-uri: https://www.reddit.com/api/v1/access_token
            authorization-url: https://www.reddit.com/api/v1/authorize